apiVersion: v1
kind: Service
metadata:
  name: password-generator-svc
spec:
  selector:
    app: password-generator
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
